# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.pb import user_pb2 as app_dot_pb_dot_user__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/pb/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/user.User/CreateUser',
                request_serializer=app_dot_pb_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/user.User/GetUserById',
                request_serializer=app_dot_pb_dot_user__pb2.GetUserByIdRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserByEmail = channel.unary_unary(
                '/user.User/GetUserByEmail',
                request_serializer=app_dot_pb_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserFromJWT = channel.unary_unary(
                '/user.User/GetUserFromJWT',
                request_serializer=app_dot_pb_dot_user__pb2.TokenRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/user.User/UpdateUser',
                request_serializer=app_dot_pb_dot_user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UserAuthentication = channel.unary_unary(
                '/user.User/UserAuthentication',
                request_serializer=app_dot_pb_dot_user__pb2.UserAuthenticationRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserFromJWT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserAuthentication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=app_dot_pb_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=app_dot_pb_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=app_dot_pb_dot_user__pb2.GetUserByIdRequest.FromString,
                    response_serializer=app_dot_pb_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=app_dot_pb_dot_user__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=app_dot_pb_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUserFromJWT': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFromJWT,
                    request_deserializer=app_dot_pb_dot_user__pb2.TokenRequest.FromString,
                    response_serializer=app_dot_pb_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=app_dot_pb_dot_user__pb2.UpdateUserRequest.FromString,
                    response_serializer=app_dot_pb_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'UserAuthentication': grpc.unary_unary_rpc_method_handler(
                    servicer.UserAuthentication,
                    request_deserializer=app_dot_pb_dot_user__pb2.UserAuthenticationRequest.FromString,
                    response_serializer=app_dot_pb_dot_user__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.User', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/CreateUser',
            app_dot_pb_dot_user__pb2.CreateUserRequest.SerializeToString,
            app_dot_pb_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/GetUserById',
            app_dot_pb_dot_user__pb2.GetUserByIdRequest.SerializeToString,
            app_dot_pb_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/GetUserByEmail',
            app_dot_pb_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
            app_dot_pb_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserFromJWT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/GetUserFromJWT',
            app_dot_pb_dot_user__pb2.TokenRequest.SerializeToString,
            app_dot_pb_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/UpdateUser',
            app_dot_pb_dot_user__pb2.UpdateUserRequest.SerializeToString,
            app_dot_pb_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserAuthentication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/UserAuthentication',
            app_dot_pb_dot_user__pb2.UserAuthenticationRequest.SerializeToString,
            app_dot_pb_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
