# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpb/user.proto\x12\x04user\"[\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\"\x14\n\x12\x43reateUserResponse\"8\n\x0cTokenRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\"<\n\x19UserAuthenticationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x15GetUserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"[\n\x11UpdateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\"c\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x32\x81\x03\n\x04User\x12\x39\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12;\n\x0bGetUserById\x12\x18.user.GetUserByIdRequest\x1a\x12.user.UserResponse\x12\x41\n\x0eGetUserByEmail\x12\x1b.user.GetUserByEmailRequest\x1a\x12.user.UserResponse\x12\x38\n\x0eGetUserFromJWT\x12\x12.user.TokenRequest\x1a\x12.user.UserResponse\x12\x39\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12I\n\x12UserAuthentication\x12\x1f.user.UserAuthenticationRequest\x1a\x12.user.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=23
  _globals['_CREATEUSERREQUEST']._serialized_end=114
  _globals['_CREATEUSERRESPONSE']._serialized_start=116
  _globals['_CREATEUSERRESPONSE']._serialized_end=136
  _globals['_TOKENREQUEST']._serialized_start=138
  _globals['_TOKENREQUEST']._serialized_end=194
  _globals['_USERAUTHENTICATIONREQUEST']._serialized_start=196
  _globals['_USERAUTHENTICATIONREQUEST']._serialized_end=256
  _globals['_GETUSERBYIDREQUEST']._serialized_start=258
  _globals['_GETUSERBYIDREQUEST']._serialized_end=290
  _globals['_GETUSERBYEMAILREQUEST']._serialized_start=292
  _globals['_GETUSERBYEMAILREQUEST']._serialized_end=330
  _globals['_UPDATEUSERREQUEST']._serialized_start=332
  _globals['_UPDATEUSERREQUEST']._serialized_end=423
  _globals['_USERRESPONSE']._serialized_start=425
  _globals['_USERRESPONSE']._serialized_end=524
  _globals['_USER']._serialized_start=527
  _globals['_USER']._serialized_end=912
# @@protoc_insertion_point(module_scope)
